services:
  pappaliigabot:
    build: .
    container_name: pappaliigabot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Helsinki
